// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP1AAGEn423_1jCUaMbK54B40G66As6vQ',
    appId: '1:268359623914:web:94582bc6df63c6a7062393',
    messagingSenderId: '268359623914',
    projectId: 'billify-001',
    authDomain: 'billify-001.firebaseapp.com',
    storageBucket: 'billify-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9z5r1OctF5XcmUme9v6_ANeL1_um7mVs',
    appId: '1:268359623914:android:455bcfde574c66c2062393',
    messagingSenderId: '268359623914',
    projectId: 'billify-001',
    storageBucket: 'billify-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Wi7tFLnrQ0VerE-pxZGVFZBpq6dwnnI',
    appId: '1:268359623914:ios:4f347cbdfe5ee0df062393',
    messagingSenderId: '268359623914',
    projectId: 'billify-001',
    storageBucket: 'billify-001.firebasestorage.app',
    iosBundleId: 'com.billify.app.billify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Wi7tFLnrQ0VerE-pxZGVFZBpq6dwnnI',
    appId: '1:268359623914:ios:4f347cbdfe5ee0df062393',
    messagingSenderId: '268359623914',
    projectId: 'billify-001',
    storageBucket: 'billify-001.firebasestorage.app',
    iosBundleId: 'com.billify.app.billify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP1AAGEn423_1jCUaMbK54B40G66As6vQ',
    appId: '1:268359623914:web:6ee132bd1b44e7a0062393',
    messagingSenderId: '268359623914',
    projectId: 'billify-001',
    authDomain: 'billify-001.firebaseapp.com',
    storageBucket: 'billify-001.firebasestorage.app',
  );
}
