import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:shared_preferences/shared_preferences.dart';

// ─────────────────────────────────────────────
// firebase_options.dart — replace with your own
// generated by: flutterfire configure
// ─────────────────────────────────────────────
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}

// ════════════════════════════════════════════════════════════
//  MAIN ENTRY POINT
// ════════════════════════════════════════════════════════════
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait mode
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const BillifyApp());
}

// ════════════════════════════════════════════════════════════
//  BRAND CONSTANTS
// ════════════════════════════════════════════════════════════
class BillifyColors {
  // Primary — Deep Indigo
  static const Color primary        = Color(0xFF1A237E);
  static const Color primaryLight   = Color(0xFF534BAE);
  static const Color primaryDark    = Color(0xFF000051);

  // Accent — Amber / Gold
  static const Color accent         = Color(0xFFFFC107);
  static const Color accentDark     = Color(0xFFC79100);

  // Status colors
  static const Color paid           = Color(0xFF2E7D32); // green
  static const Color unpaid         = Color(0xFFC62828); // red
  static const Color draft          = Color(0xFF757575); // grey
  static const Color overdue        = Color(0xFFE65100); // orange

  // Neutral
  static const Color background     = Color(0xFFF5F6FA);
  static const Color surface        = Color(0xFFFFFFFF);
  static const Color textPrimary    = Color(0xFF1A1A2E);
  static const Color textSecondary  = Color(0xFF6B7280);
  static const Color divider        = Color(0xFFE5E7EB);

  // Dark theme
  static const Color darkBackground = Color(0xFF0D0D1A);
  static const Color darkSurface    = Color(0xFF1C1C2E);
  static const Color darkCard       = Color(0xFF252538);
}

// ════════════════════════════════════════════════════════════
//  APP THEMES
// ════════════════════════════════════════════════════════════
class BillifyTheme {
  // ── Light Theme ──
  static ThemeData get light {
    final base = ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: BillifyColors.primary,
        brightness: Brightness.light,
        primary:   BillifyColors.primary,
        secondary: BillifyColors.accent,
        surface:   BillifyColors.surface,
        background: BillifyColors.background,
      ),
      scaffoldBackgroundColor: BillifyColors.background,
    );

    return base.copyWith(
      textTheme: GoogleFonts.poppinsTextTheme(base.textTheme).copyWith(
        // Display / Heading — Poppins
        displayLarge:  GoogleFonts.poppins(fontSize: 32, fontWeight: FontWeight.w700, color: BillifyColors.textPrimary),
        displayMedium: GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w700, color: BillifyColors.textPrimary),
        displaySmall:  GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.w600, color: BillifyColors.textPrimary),
        headlineLarge: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w600, color: BillifyColors.textPrimary),
        headlineMedium:GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w600, color: BillifyColors.textPrimary),
        headlineSmall: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600, color: BillifyColors.textPrimary),
        // Body — Nunito
        bodyLarge:     GoogleFonts.nunito(fontSize: 16, fontWeight: FontWeight.w400, color: BillifyColors.textPrimary),
        bodyMedium:    GoogleFonts.nunito(fontSize: 14, fontWeight: FontWeight.w400, color: BillifyColors.textPrimary),
        bodySmall:     GoogleFonts.nunito(fontSize: 12, fontWeight: FontWeight.w400, color: BillifyColors.textSecondary),
        labelLarge:    GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w600, color: BillifyColors.primary),
        labelMedium:   GoogleFonts.nunito(fontSize: 12, fontWeight: FontWeight.w500, color: BillifyColors.textSecondary),
        labelSmall:    GoogleFonts.nunito(fontSize: 11, fontWeight: FontWeight.w400, color: BillifyColors.textSecondary),
      ),
      appBarTheme: AppBarTheme(
        backgroundColor:  BillifyColors.primary,
        foregroundColor:  Colors.white,
        elevation:        0,
        centerTitle:      true,
        titleTextStyle:   GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w600, color: Colors.white),
        iconTheme:        const IconThemeData(color: Colors.white),
        systemOverlayStyle: SystemUiOverlayStyle.light,
      ),
      cardTheme: CardThemeData(
        color:      BillifyColors.surface,
        elevation:  2,
        shadowColor: BillifyColors.primary.withOpacity(0.08),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor:  BillifyColors.primary,
          foregroundColor:  Colors.white,
          elevation:        2,
          minimumSize:      const Size(double.infinity, 52),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          textStyle: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: BillifyColors.primary,
          side: const BorderSide(color: BillifyColors.primary, width: 1.5),
          minimumSize: const Size(double.infinity, 52),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          textStyle: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled:      true,
        fillColor:   BillifyColors.surface,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: BillifyColors.divider),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: BillifyColors.divider, width: 1.5),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: BillifyColors.primary, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: BillifyColors.unpaid, width: 1.5),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        labelStyle: GoogleFonts.nunito(color: BillifyColors.textSecondary),
        hintStyle:  GoogleFonts.nunito(color: BillifyColors.textSecondary.withOpacity(0.7)),
      ),
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: BillifyColors.primary,
        foregroundColor: Colors.white,
        elevation: 4,
      ),
      bottomNavigationBarTheme: const BottomNavigationBarThemeData(
        backgroundColor: BillifyColors.surface,
        selectedItemColor: BillifyColors.primary,
        unselectedItemColor: BillifyColors.textSecondary,
        elevation: 8,
      ),
      drawerTheme: const DrawerThemeData(
        backgroundColor: BillifyColors.surface,
        elevation: 4,
      ),
      dividerTheme: const DividerThemeData(
        color: BillifyColors.divider,
        thickness: 1,
      ),
      chipTheme: ChipThemeData(
        backgroundColor:    BillifyColors.background,
        selectedColor:      BillifyColors.primary.withOpacity(0.15),
        labelStyle:         GoogleFonts.nunito(fontSize: 12, fontWeight: FontWeight.w500),
        side: const BorderSide(color: BillifyColors.divider),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      ),
      snackBarTheme: SnackBarThemeData(
        backgroundColor: BillifyColors.darkSurface,
        contentTextStyle: GoogleFonts.nunito(color: Colors.white),
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
      dialogTheme: DialogThemeData(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        titleTextStyle: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w600, color: BillifyColors.textPrimary),
        contentTextStyle: GoogleFonts.nunito(fontSize: 14, color: BillifyColors.textSecondary),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateProperty.resolveWith((states) {
          if (states.contains(MaterialState.selected)) return BillifyColors.primary;
          return Colors.transparent;
        }),
        side: const BorderSide(color: BillifyColors.primary, width: 2),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
      ),
      progressIndicatorTheme: const ProgressIndicatorThemeData(
        color: BillifyColors.primary,
      ),
    );
  }

  // ── Dark Theme ──
  static ThemeData get dark {
    final base = ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: BillifyColors.primary,
        brightness: Brightness.dark,
        primary:    BillifyColors.primaryLight,
        secondary:  BillifyColors.accent,
        surface:    BillifyColors.darkSurface,
        background: BillifyColors.darkBackground,
      ),
      scaffoldBackgroundColor: BillifyColors.darkBackground,
    );

    return base.copyWith(
      textTheme: GoogleFonts.poppinsTextTheme(base.textTheme).copyWith(
        displayLarge:  GoogleFonts.poppins(fontSize: 32, fontWeight: FontWeight.w700, color: Colors.white),
        displayMedium: GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w700, color: Colors.white),
        headlineLarge: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w600, color: Colors.white),
        bodyLarge:     GoogleFonts.nunito(fontSize: 16, color: Colors.white70),
        bodyMedium:    GoogleFonts.nunito(fontSize: 14, color: Colors.white70),
        bodySmall:     GoogleFonts.nunito(fontSize: 12, color: Colors.white54),
      ),
      appBarTheme: AppBarTheme(
        backgroundColor:    BillifyColors.darkSurface,
        foregroundColor:    Colors.white,
        elevation:          0,
        centerTitle:        true,
        titleTextStyle:     GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w600, color: Colors.white),
        systemOverlayStyle: SystemUiOverlayStyle.light,
      ),
      cardTheme: CardThemeData(
        color:     BillifyColors.darkCard,
        elevation: 2,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: BillifyColors.primaryLight,
          foregroundColor: Colors.white,
          minimumSize: const Size(double.infinity, 52),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          textStyle: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled:    true,
        fillColor: BillifyColors.darkCard,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: Colors.white12),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide(color: Colors.white24),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: BillifyColors.primaryLight, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        labelStyle: GoogleFonts.nunito(color: Colors.white54),
        hintStyle:  GoogleFonts.nunito(color: Colors.white38),
      ),
      floatingActionButtonTheme: const FloatingActionButtonThemeData(
        backgroundColor: BillifyColors.primaryLight,
        foregroundColor: Colors.white,
      ),
      drawerTheme: const DrawerThemeData(
        backgroundColor: BillifyColors.darkSurface,
      ),
    );
  }
}

// ════════════════════════════════════════════════════════════
//  ROUTE NAMES
// ════════════════════════════════════════════════════════════
class AppRoutes {
  static const splash           = '/splash';
  static const login            = '/login';
  static const register         = '/register';
  static const forgotPassword   = '/forgot-password';
  static const termsConditions  = '/terms-conditions';
  static const dashboard        = '/dashboard';
  static const invoices         = '/invoices';
  static const invoiceCreate    = '/invoice-create';
  static const invoiceEdit      = '/invoice-edit';
  static const invoiceDetail    = '/invoice-detail';
  static const expenses         = '/expenses';
  static const expenseAdd       = '/expense-add';
  static const profile          = '/profile';
  static const settings         = '/settings';
}

// ════════════════════════════════════════════════════════════
//  AUTH MIDDLEWARE — protects dashboard & inner routes
// ════════════════════════════════════════════════════════════
class AuthMiddleware extends GetMiddleware {
  @override
  int? get priority => 1;

  @override
  RouteSettings? redirect(String? route) {
    final user = FirebaseAuth.instance.currentUser;

    // Not logged in → go to login
    if (user == null) {
      return const RouteSettings(name: AppRoutes.login);
    }
    return null; // allow
  }
}

// ────────────────────────────────────────────────────────────
//  TERMS MIDDLEWARE — checks if terms have been accepted
// ────────────────────────────────────────────────────────────
class TermsMiddleware extends GetMiddleware {
  @override
  int? get priority => 2;

  @override
  RouteSettings? redirect(String? route) {
    // SharedPreferences sync check (fast path)
    // Full async check happens in SplashScreen
    return null;
  }
}

// ════════════════════════════════════════════════════════════
//  ROOT APP WIDGET
// ════════════════════════════════════════════════════════════
class BillifyApp extends StatelessWidget {
  const BillifyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      // ── Identity ──
      title:           'Billify',
      debugShowCheckedModeBanner: false,

      // ── Themes ──
      theme:     BillifyTheme.light,
      darkTheme: BillifyTheme.dark,
      themeMode: ThemeMode.system,

      // ── Default route ──
      initialRoute: AppRoutes.splash,

      // ── All named routes ──
      getPages: [
        // Splash
        GetPage(
          name:       AppRoutes.splash,
          page:       () => const SplashScreen(),
          transition: Transition.fadeIn,
        ),

        // Auth
        GetPage(
          name:       AppRoutes.login,
          page:       () => const LoginScreen(),
          transition: Transition.fadeIn,
        ),
        GetPage(
          name:       AppRoutes.register,
          page:       () => const RegisterScreen(),
          transition: Transition.rightToLeft,
        ),
        GetPage(
          name:       AppRoutes.forgotPassword,
          page:       () => const ForgotPasswordScreen(),
          transition: Transition.rightToLeft,
        ),

        // Onboarding
        GetPage(
          name:       AppRoutes.termsConditions,
          page:       () => const TermsConditionsScreen(),
          transition: Transition.upToDown,
          middlewares: [AuthMiddleware()],
        ),

        // Main App — protected by AuthMiddleware
        GetPage(
          name:       AppRoutes.dashboard,
          page:       () => const DashboardScreen(),
          transition: Transition.fadeIn,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.invoices,
          page:       () => const InvoiceListScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.invoiceCreate,
          page:       () => const InvoiceCreateScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.invoiceEdit,
          page:       () => const InvoiceEditScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.invoiceDetail,
          page:       () => const InvoiceDetailScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.expenses,
          page:       () => const ExpenseListScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.expenseAdd,
          page:       () => const AddExpenseScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.profile,
          page:       () => const ProfileScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
        GetPage(
          name:       AppRoutes.settings,
          page:       () => const SettingsScreen(),
          transition: Transition.rightToLeft,
          middlewares: [AuthMiddleware()],
        ),
      ],
    );
  }
}

// ════════════════════════════════════════════════════════════
//  SPLASH SCREEN — routing logic
// ════════════════════════════════════════════════════════════
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double>   _fadeAnim;
  late Animation<double>   _scaleAnim;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync:    this,
      duration: const Duration(milliseconds: 1200),
    );
    _fadeAnim  = Tween<double>(begin: 0, end: 1).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeIn),
    );
    _scaleAnim = Tween<double>(begin: 0.7, end: 1).animate(
      CurvedAnimation(parent: _controller, curve: Curves.elasticOut),
    );

    _controller.forward();
    _navigate();
  }

  /// Decides where to send the user after splash
  Future<void> _navigate() async {
    await Future.delayed(const Duration(milliseconds: 2200));

    final user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      // Not logged in → Login
      Get.offAllNamed(AppRoutes.login);
      return;
    }

    // Check if terms have been accepted (Firestore)
    try {
      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .get();

      final termsAccepted = doc.data()?['termsAccepted'] ?? false;

      if (termsAccepted) {
        Get.offAllNamed(AppRoutes.dashboard);
      } else {
        Get.offAllNamed(AppRoutes.termsConditions);
      }
    } catch (_) {
      // Fallback: send to login on any Firestore error
      Get.offAllNamed(AppRoutes.login);
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: BillifyColors.primary,
      body: Center(
        child: FadeTransition(
          opacity: _fadeAnim,
          child: ScaleTransition(
            scale: _scaleAnim,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                // Logo container
                Container(
                  width:  100,
                  height: 100,
                  decoration: BoxDecoration(
                    color:        Colors.white,
                    borderRadius: BorderRadius.circular(24),
                    boxShadow: [
                      BoxShadow(
                        color:      Colors.black.withOpacity(0.2),
                        blurRadius: 20,
                        offset: const Offset(0, 8),
                      ),
                    ],
                  ),
                  child: const Center(
                    child: Icon(
                      Icons.receipt_long_rounded,
                      color: BillifyColors.primary,
                      size: 56,
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                // App name
                Text(
                  'Billify',
                  style: GoogleFonts.poppins(
                    fontSize:   38,
                    fontWeight: FontWeight.w800,
                    color:      Colors.white,
                    letterSpacing: 1.5,
                  ),
                ),
                const SizedBox(height: 6),
                Text(
                  'Smart Invoicing. Simple Finance.',
                  style: GoogleFonts.nunito(
                    fontSize: 14,
                    color:    Colors.white70,
                    letterSpacing: 0.5,
                  ),
                ),
                const SizedBox(height: 40),
                // Loading indicator
                SizedBox(
                  width:  40,
                  height: 40,
                  child: CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(
                      BillifyColors.accent,
                    ),
                    strokeWidth: 3,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// ════════════════════════════════════════════════════════════
//  SIDE DRAWER — shared across all main screens
// ════════════════════════════════════════════════════════════
class BillifyDrawer extends StatelessWidget {
  final String activeRoute;
  const BillifyDrawer({super.key, required this.activeRoute});

  void _logout() {
    Get.dialog(
      AlertDialog(
        title: const Text('Logout'),
        content: const Text('Are you sure you want to logout from Billify?'),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: BillifyColors.unpaid,
            ),
            onPressed: () async {
              await FirebaseAuth.instance.signOut();
              Get.offAllNamed(AppRoutes.login);
            },
            child: const Text('Logout'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = FirebaseAuth.instance.currentUser;

    return Drawer(
      child: Column(
        children: [
          // ── Drawer Header ──
          UserAccountsDrawerHeader(
            decoration: const BoxDecoration(
              color: BillifyColors.primary,
            ),
            currentAccountPicture: CircleAvatar(
              backgroundColor: Colors.white,
              backgroundImage: user?.photoURL != null
                  ? NetworkImage(user!.photoURL!)
                  : null,
              child: user?.photoURL == null
                  ? const Icon(Icons.person, color: BillifyColors.primary, size: 36)
                  : null,
            ),
            accountName: Text(
              user?.displayName ?? 'Billify User',
              style: GoogleFonts.poppins(
                fontWeight: FontWeight.w600,
                fontSize:   15,
              ),
            ),
            accountEmail: Text(
              user?.email ?? '',
              style: GoogleFonts.nunito(fontSize: 13),
            ),
          ),

          // ── Nav Items ──
          Expanded(
            child: ListView(
              padding: EdgeInsets.zero,
              children: [
                _NavItem(
                  icon:        Icons.dashboard_rounded,
                  label:       'Dashboard',
                  route:       AppRoutes.dashboard,
                  activeRoute: activeRoute,
                ),
                _NavItem(
                  icon:        Icons.receipt_long_rounded,
                  label:       'Invoices',
                  route:       AppRoutes.invoices,
                  activeRoute: activeRoute,
                ),
                _NavItem(
                  icon:        Icons.account_balance_wallet_rounded,
                  label:       'Expenses & Income',
                  route:       AppRoutes.expenses,
                  activeRoute: activeRoute,
                ),
                _NavItem(
                  icon:        Icons.person_rounded,
                  label:       'My Profile',
                  route:       AppRoutes.profile,
                  activeRoute: activeRoute,
                ),
                const Divider(height: 1),
                _NavItem(
                  icon:        Icons.description_rounded,
                  label:       'Terms & Conditions',
                  route:       AppRoutes.termsConditions,
                  activeRoute: activeRoute,
                ),
                _NavItem(
                  icon:        Icons.settings_rounded,
                  label:       'Settings',
                  route:       AppRoutes.settings,
                  activeRoute: activeRoute,
                ),
              ],
            ),
          ),

          // ── Logout ──
          const Divider(height: 1),
          ListTile(
            leading: const Icon(Icons.logout_rounded, color: BillifyColors.unpaid),
            title: Text(
              'Logout',
              style: GoogleFonts.nunito(
                color:      BillifyColors.unpaid,
                fontWeight: FontWeight.w600,
              ),
            ),
            onTap: _logout,
          ),
          const SizedBox(height: 8),

          // ── Branding footer ──
          Padding(
            padding: const EdgeInsets.only(bottom: 16),
            child: Text(
              'Billify v1.0.0',
              style: GoogleFonts.nunito(
                fontSize: 11,
                color:    BillifyColors.textSecondary,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _NavItem extends StatelessWidget {
  final IconData icon;
  final String   label;
  final String   route;
  final String   activeRoute;

  const _NavItem({
    required this.icon,
    required this.label,
    required this.route,
    required this.activeRoute,
  });

  @override
  Widget build(BuildContext context) {
    final isActive = activeRoute == route;
    return ListTile(
      leading: Icon(
        icon,
        color: isActive ? BillifyColors.primary : BillifyColors.textSecondary,
      ),
      title: Text(
        label,
        style: GoogleFonts.nunito(
          fontWeight: isActive ? FontWeight.w700 : FontWeight.w500,
          color:      isActive ? BillifyColors.primary : BillifyColors.textPrimary,
        ),
      ),
      tileColor: isActive ? BillifyColors.primary.withOpacity(0.08) : null,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 2),
      onTap: () {
        Get.back(); // close drawer
        if (activeRoute != route) {
          Get.offNamed(route);
        }
      },
    );
  }
}

// ════════════════════════════════════════════════════════════
//  AUTH SCREENS
// ════════════════════════════════════════════════════════════

// ── Login Screen ──────────────────────────────────────────
class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});
  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _emailCtrl    = TextEditingController();
  final _passwordCtrl = TextEditingController();
  bool  _obscure      = true;
  bool  _loading      = false;

  Future<void> _login() async {
    if (_emailCtrl.text.trim().isEmpty || _passwordCtrl.text.isEmpty) {
      Get.snackbar('Error', 'Please fill in all fields',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
      return;
    }
    setState(() => _loading = true);
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email:    _emailCtrl.text.trim(),
        password: _passwordCtrl.text,
      );
      // Check terms
      final uid = FirebaseAuth.instance.currentUser!.uid;
      final doc = await FirebaseFirestore.instance.collection('users').doc(uid).get();
      final termsAccepted = doc.data()?['termsAccepted'] ?? false;
      Get.offAllNamed(termsAccepted ? AppRoutes.dashboard : AppRoutes.termsConditions);
    } on FirebaseAuthException catch (e) {
      Get.snackbar('Login Failed', e.message ?? 'An error occurred',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _forgotPassword() async {
    if (_emailCtrl.text.trim().isEmpty) {
      Get.snackbar('Enter Email', 'Please enter your email to reset password',
          backgroundColor: BillifyColors.overdue, colorText: Colors.white);
      return;
    }
    try {
      await FirebaseAuth.instance.sendPasswordResetEmail(email: _emailCtrl.text.trim());
      Get.snackbar('Email Sent', 'Password reset link sent to ${_emailCtrl.text.trim()}',
          backgroundColor: BillifyColors.paid, colorText: Colors.white);
    } catch (e) {
      Get.snackbar('Error', 'Could not send reset email',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: BillifyColors.background,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Logo
              Center(
                child: Container(
                  width: 72, height: 72,
                  decoration: BoxDecoration(
                    color: BillifyColors.primary,
                    borderRadius: BorderRadius.circular(18),
                  ),
                  child: const Icon(Icons.receipt_long_rounded, color: Colors.white, size: 40),
                ),
              ),
              const SizedBox(height: 20),
              Center(
                child: Text('Billify',
                    style: GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w800,
                        color: BillifyColors.primary)),
              ),
              Center(
                child: Text('Sign in to your account',
                    style: GoogleFonts.nunito(color: BillifyColors.textSecondary)),
              ),
              const SizedBox(height: 40),

              // Email
              TextField(
                controller: _emailCtrl,
                keyboardType: TextInputType.emailAddress,
                decoration: const InputDecoration(
                  labelText: 'Email Address',
                  prefixIcon: Icon(Icons.email_rounded, color: BillifyColors.primary),
                ),
              ),
              const SizedBox(height: 16),

              // Password
              TextField(
                controller: _passwordCtrl,
                obscureText: _obscure,
                decoration: InputDecoration(
                  labelText: 'Password',
                  prefixIcon: const Icon(Icons.lock_rounded, color: BillifyColors.primary),
                  suffixIcon: IconButton(
                    icon: Icon(_obscure ? Icons.visibility_off : Icons.visibility,
                        color: BillifyColors.textSecondary),
                    onPressed: () => setState(() => _obscure = !_obscure),
                  ),
                ),
              ),
              const SizedBox(height: 8),

              // Forgot password
              Align(
                alignment: Alignment.centerRight,
                child: TextButton(
                  onPressed: _forgotPassword,
                  child: Text('Forgot Password?',
                      style: GoogleFonts.nunito(color: BillifyColors.primary, fontWeight: FontWeight.w600)),
                ),
              ),
              const SizedBox(height: 24),

              // Login button
              _loading
                  ? const Center(child: CircularProgressIndicator())
                  : ElevatedButton(
                onPressed: _login,
                child: const Text('Login'),
              ),
              const SizedBox(height: 16),

              // Register link
              Center(
                child: GestureDetector(
                  onTap: () => Get.toNamed(AppRoutes.register),
                  child: RichText(
                    text: TextSpan(
                      text: "Don't have an account? ",
                      style: GoogleFonts.nunito(color: BillifyColors.textSecondary),
                      children: [
                        TextSpan(
                          text: 'Register',
                          style: GoogleFonts.nunito(
                              color: BillifyColors.primary, fontWeight: FontWeight.w700),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ── Register Screen ───────────────────────────────────────
class RegisterScreen extends StatefulWidget {
  const RegisterScreen({super.key});
  @override
  State<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends State<RegisterScreen> {
  final _nameCtrl         = TextEditingController();
  final _businessCtrl     = TextEditingController();
  final _emailCtrl        = TextEditingController();
  final _passwordCtrl     = TextEditingController();
  final _confirmPassCtrl  = TextEditingController();
  bool  _obscure          = true;
  bool  _loading          = false;

  Future<void> _register() async {
    if (_nameCtrl.text.trim().isEmpty ||
        _businessCtrl.text.trim().isEmpty ||
        _emailCtrl.text.trim().isEmpty ||
        _passwordCtrl.text.isEmpty) {
      Get.snackbar('Error', 'Please fill in all fields',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
      return;
    }
    if (_passwordCtrl.text != _confirmPassCtrl.text) {
      Get.snackbar('Error', 'Passwords do not match',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
      return;
    }
    if (_passwordCtrl.text.length < 6) {
      Get.snackbar('Error', 'Password must be at least 6 characters',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
      return;
    }

    setState(() => _loading = true);
    try {
      final cred = await FirebaseAuth.instance.createUserWithEmailAndPassword(
        email:    _emailCtrl.text.trim(),
        password: _passwordCtrl.text,
      );

      // Update display name
      await cred.user!.updateDisplayName(_nameCtrl.text.trim());

      // Create Firestore user profile document
      await FirebaseFirestore.instance.collection('users').doc(cred.user!.uid).set({
        'uid':              cred.user!.uid,
        'fullName':         _nameCtrl.text.trim(),
        'businessName':     _businessCtrl.text.trim(),
        'email':            _emailCtrl.text.trim(),
        'phone':            '',
        'address':          '',
        'gstNumber':        '',
        'photoUrl':         '',
        'termsAccepted':    false,
        'termsAcceptedAt':  null,
        'createdAt':        FieldValue.serverTimestamp(),
      });

      Get.offAllNamed(AppRoutes.termsConditions);
    } on FirebaseAuthException catch (e) {
      Get.snackbar('Registration Failed', e.message ?? 'An error occurred',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Create Account')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            const SizedBox(height: 8),
            Text('Join Billify',
                style: GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w700,
                    color: BillifyColors.primary)),
            Text('Create your free account',
                style: GoogleFonts.nunito(color: BillifyColors.textSecondary)),
            const SizedBox(height: 32),

            TextField(
              controller: _nameCtrl,
              decoration: const InputDecoration(
                labelText: 'Full Name',
                prefixIcon: Icon(Icons.person_rounded, color: BillifyColors.primary),
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _businessCtrl,
              decoration: const InputDecoration(
                labelText: 'Business Name',
                prefixIcon: Icon(Icons.business_rounded, color: BillifyColors.primary),
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _emailCtrl,
              keyboardType: TextInputType.emailAddress,
              decoration: const InputDecoration(
                labelText: 'Email Address',
                prefixIcon: Icon(Icons.email_rounded, color: BillifyColors.primary),
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _passwordCtrl,
              obscureText: _obscure,
              decoration: InputDecoration(
                labelText: 'Password',
                prefixIcon: const Icon(Icons.lock_rounded, color: BillifyColors.primary),
                suffixIcon: IconButton(
                  icon: Icon(_obscure ? Icons.visibility_off : Icons.visibility,
                      color: BillifyColors.textSecondary),
                  onPressed: () => setState(() => _obscure = !_obscure),
                ),
              ),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _confirmPassCtrl,
              obscureText: _obscure,
              decoration: const InputDecoration(
                labelText: 'Confirm Password',
                prefixIcon: Icon(Icons.lock_outline_rounded, color: BillifyColors.primary),
              ),
            ),
            const SizedBox(height: 32),

            _loading
                ? const CircularProgressIndicator()
                : ElevatedButton(
              onPressed: _register,
              child: const Text('Create Account'),
            ),
            const SizedBox(height: 16),

            GestureDetector(
              onTap: () => Get.back(),
              child: RichText(
                text: TextSpan(
                  text: 'Already have an account? ',
                  style: GoogleFonts.nunito(color: BillifyColors.textSecondary),
                  children: [
                    TextSpan(
                      text: 'Login',
                      style: GoogleFonts.nunito(
                          color: BillifyColors.primary, fontWeight: FontWeight.w700),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── Forgot Password Screen ────────────────────────────────
class ForgotPasswordScreen extends StatelessWidget {
  const ForgotPasswordScreen({super.key});
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: const Text('Forgot Password')),
    body: Center(
      child: Text('Forgot Password Screen — Phase 2',
          style: GoogleFonts.nunito(color: BillifyColors.textSecondary)),
    ),
  );
}

// ════════════════════════════════════════════════════════════
//  TERMS & CONDITIONS SCREEN
// ════════════════════════════════════════════════════════════
class TermsConditionsScreen extends StatefulWidget {
  const TermsConditionsScreen({super.key});
  @override
  State<TermsConditionsScreen> createState() => _TermsConditionsScreenState();
}

class _TermsConditionsScreenState extends State<TermsConditionsScreen> {
  bool _scrolledToBottom = false;
  bool _agreed           = false;
  bool _loading          = false;
  final ScrollController _scrollCtrl = ScrollController();

  @override
  void initState() {
    super.initState();
    _scrollCtrl.addListener(() {
      if (_scrollCtrl.offset >= _scrollCtrl.position.maxScrollExtent - 40) {
        if (!_scrolledToBottom) setState(() => _scrolledToBottom = true);
      }
    });
  }

  @override
  void dispose() {
    _scrollCtrl.dispose();
    super.dispose();
  }

  Future<void> _accept() async {
    if (!_agreed) return;
    setState(() => _loading = true);
    try {
      final uid = FirebaseAuth.instance.currentUser!.uid;
      await FirebaseFirestore.instance.collection('users').doc(uid).update({
        'termsAccepted':   true,
        'termsAcceptedAt': FieldValue.serverTimestamp(),
      });
      Get.offAllNamed(AppRoutes.dashboard);
    } catch (e) {
      Get.snackbar('Error', 'Could not save acceptance. Please try again.',
          backgroundColor: BillifyColors.unpaid, colorText: Colors.white);
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Terms & Conditions')),
      body: Column(
        children: [
          // Scroll hint
          if (!_scrolledToBottom)
            Container(
              color: BillifyColors.accent.withOpacity(0.15),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              child: Row(
                children: [
                  const Icon(Icons.info_outline, color: BillifyColors.overdue, size: 18),
                  const SizedBox(width: 8),
                  Text('Please scroll to read all terms before proceeding.',
                      style: GoogleFonts.nunito(color: BillifyColors.overdue, fontSize: 13)),
                ],
              ),
            ),

          // Terms content
          Expanded(
            child: SingleChildScrollView(
              controller: _scrollCtrl,
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header
                  Center(
                    child: Column(
                      children: [
                        Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: BillifyColors.primary.withOpacity(0.1),
                            shape: BoxShape.circle,
                          ),
                          child: const Icon(Icons.description_rounded,
                              color: BillifyColors.primary, size: 40),
                        ),
                        const SizedBox(height: 12),
                        Text('Terms & Conditions',
                            style: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w700,
                                color: BillifyColors.primary)),
                        Text('Last updated: January 2025',
                            style: GoogleFonts.nunito(color: BillifyColors.textSecondary, fontSize: 12)),
                      ],
                    ),
                  ),
                  const SizedBox(height: 28),
                  _TermsClause(number: '1', title: 'Lawful Use Only',
                      body: 'Billify is intended for lawful invoice generation and personal or '
                          'business expense tracking only. Any use of this application for '
                          'illegal purposes is strictly prohibited.'),
                  _TermsClause(number: '2', title: 'Data Privacy & Security',
                      body: 'All user data is stored securely using Google Firebase. Billify '
                          'does not sell, share, or rent your personal or business data to '
                          'any third parties under any circumstances.'),
                  _TermsClause(number: '3', title: 'Invoice Accuracy',
                      body: 'You are solely responsible for the accuracy and legality of any '
                          'invoice you generate using this app. Billify does not verify the '
                          'correctness of the information you input.'),
                  _TermsClause(number: '4', title: 'No Payment Processing',
                      body: 'Billify does not process, collect, or facilitate any payments. '
                          'It only generates invoices for record-keeping and tracking purposes. '
                          'Any actual payment transactions occur outside this app.'),
                  _TermsClause(number: '5', title: 'GST Disclaimer',
                      body: 'GST calculations provided in this app are for reference only '
                          'and may not reflect the latest GST rates or rules. Please consult '
                          'a qualified Chartered Accountant for official GST filings and compliance.'),
                  _TermsClause(number: '6', title: 'Limitation of Liability',
                      body: 'The developers and owners of Billify are not liable for any '
                          'financial, legal, or business disputes, losses, or damages arising '
                          'from the use of this application or the invoices generated through it.'),
                  _TermsClause(number: '7', title: 'Account Termination',
                      body: 'Misuse of this app for fraudulent invoicing, illegal billing '
                          'activities, or any violation of these terms may result in immediate '
                          'account suspension or permanent termination without prior notice.'),
                  _TermsClause(number: '8', title: 'Updates to Terms',
                      body: 'Billify reserves the right to update these Terms & Conditions '
                          'at any time without prior notice. Continued use of the application '
                          'after any changes implies your acceptance of the updated terms.'),

                  const SizedBox(height: 24),
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: BillifyColors.primary.withOpacity(0.06),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: BillifyColors.primary.withOpacity(0.2)),
                    ),
                    child: Text(
                      'By using Billify, you confirm that you are at least 18 years old '
                          'and legally capable of entering into binding agreements.',
                      style: GoogleFonts.nunito(color: BillifyColors.primary, fontSize: 13,
                          fontWeight: FontWeight.w500),
                    ),
                  ),
                  const SizedBox(height: 32),
                ],
              ),
            ),
          ),

          // Bottom — checkbox + button
          Container(
            decoration: BoxDecoration(
              color: Theme.of(context).scaffoldBackgroundColor,
              boxShadow: [
                BoxShadow(
                  color:      Colors.black.withOpacity(0.08),
                  blurRadius: 12,
                  offset: const Offset(0, -4),
                ),
              ],
            ),
            padding: const EdgeInsets.all(20),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                // Checkbox
                GestureDetector(
                  onTap: _scrolledToBottom
                      ? () => setState(() => _agreed = !_agreed)
                      : null,
                  child: Row(
                    children: [
                      Checkbox(
                        value:     _agreed,
                        onChanged: _scrolledToBottom
                            ? (val) => setState(() => _agreed = val ?? false)
                            : null,
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          'I have read and agree to the Terms & Conditions of Billify.',
                          style: GoogleFonts.nunito(
                            fontSize:   14,
                            fontWeight: FontWeight.w600,
                            color: _scrolledToBottom
                                ? BillifyColors.textPrimary
                                : BillifyColors.textSecondary,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 12),

                // Proceed button
                _loading
                    ? const CircularProgressIndicator()
                    : ElevatedButton(
                  onPressed: (_agreed && !_loading) ? _accept : null,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _agreed
                        ? BillifyColors.primary
                        : BillifyColors.divider,
                  ),
                  child: const Text('Proceed to Billify'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _TermsClause extends StatelessWidget {
  final String number, title, body;
  const _TermsClause({required this.number, required this.title, required this.body});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 28, height: 28,
            decoration: BoxDecoration(
              color: BillifyColors.primary,
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Text(number,
                  style: GoogleFonts.poppins(color: Colors.white, fontSize: 13,
                      fontWeight: FontWeight.w600)),
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w600,
                        color: BillifyColors.textPrimary)),
                const SizedBox(height: 4),
                Text(body,
                    style: GoogleFonts.nunito(fontSize: 14, color: BillifyColors.textSecondary,
                        height: 1.5)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ════════════════════════════════════════════════════════════
//  PLACEHOLDER SCREENS
//  (Full implementation added in subsequent phases)
// ════════════════════════════════════════════════════════════
class _PlaceholderScreen extends StatelessWidget {
  final String   title;
  final IconData icon;
  final String   route;

  const _PlaceholderScreen({
    required this.title,
    required this.icon,
    required this.route,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      drawer: BillifyDrawer(activeRoute: route),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 72, color: BillifyColors.primary.withOpacity(0.3)),
            const SizedBox(height: 16),
            Text(title,
                style: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w600,
                    color: BillifyColors.textPrimary)),
            const SizedBox(height: 8),
            Text('Full screen — Phase 2',
                style: GoogleFonts.nunito(color: BillifyColors.textSecondary)),
          ],
        ),
      ),
    );
  }
}

// Individual placeholder widgets wired to named routes
class DashboardScreen    extends StatelessWidget { const DashboardScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Dashboard',        icon: Icons.dashboard_rounded,                route: AppRoutes.dashboard); }

class InvoiceListScreen  extends StatelessWidget { const InvoiceListScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Invoices',         icon: Icons.receipt_long_rounded,             route: AppRoutes.invoices); }

class InvoiceCreateScreen extends StatelessWidget { const InvoiceCreateScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Create Invoice',   icon: Icons.add_circle_rounded,               route: AppRoutes.invoiceCreate); }

class InvoiceEditScreen  extends StatelessWidget { const InvoiceEditScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Edit Invoice',     icon: Icons.edit_rounded,                     route: AppRoutes.invoiceEdit); }

class InvoiceDetailScreen extends StatelessWidget { const InvoiceDetailScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Invoice Detail',   icon: Icons.receipt_rounded,                  route: AppRoutes.invoiceDetail); }

class ExpenseListScreen  extends StatelessWidget { const ExpenseListScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Expenses & Income',icon: Icons.account_balance_wallet_rounded,    route: AppRoutes.expenses); }

class AddExpenseScreen   extends StatelessWidget { const AddExpenseScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Add Entry',        icon: Icons.add_rounded,                      route: AppRoutes.expenseAdd); }

class ProfileScreen      extends StatelessWidget { const ProfileScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'My Profile',       icon: Icons.person_rounded,                   route: AppRoutes.profile); }

class SettingsScreen     extends StatelessWidget { const SettingsScreen({super.key});
@override Widget build(BuildContext c) => const _PlaceholderScreen(title: 'Settings',         icon: Icons.settings_rounded,                 route: AppRoutes.settings); }